### ISSUE TITLE
Singleplayer worlds don't work

### ISSUE THREAD

**Issue by Hal1co** [Provismet/Provi-Origins#7] opened 2024-01-28 12:12 UTC
### Type of Error

Crash

### Description

Whenever I try to open a world it gives me this error message
Some other mods that I use don't have versions for 1.20.2, so I can't use 1.6.1
![image](https://github.com/Provismet/Provi-Origins/assets/147345790/6b34782b-d03d-4fcb-b029-eb90e79c7601)

### Mod Version

1.5.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

```bash
- Open the game
- Singleplayer
- Create new world
- 100%
- Joining world
- Connection lost (image above)
```

**Comment by Provismet** [comment] 2024-01-28 13:05
This is unfortunately a duplicate of #6 and isn't an issue I can solve.

This bug is occuring inside of Apoli (one of the mods within Origins itself) and it's happening because Apoli is failing to get the power list correctly. (\u0000 is a NUL character)

Other person didn't find a solution to the problem, but it's likely the issue is specific to your computer. I don't get this issue myself, and neither do my testers. I'd be happy to help you troubleshoot this, however.

**Comment by Provismet** [comment] 2024-01-28 13:20
Could you give me more information about your Minecraft environment:
- Fabric version
- Fabric API version
- Any other mods you have in your mods folder
- The file sizes of each mod (the other person who reported this had different file sizes to me)

So far this issue is new (which is odd for an older version of the mod that never experienced any issue like this before) and has been non-reproducible. With more information it could hopefully be presented to the Apoli team.

**Comment by Hal1co** [comment] 2024-01-28 13:36
Fabric - 0.15.6
Fapric API - 0.91.0
Mods & sizes - I'll send a picture. I hope it's okay :')
![image](https://github.com/Provismet/Provi-Origins/assets/147345790/0bc67f4f-7e7c-4a57-a1ab-d70bb4c8d693)

**Comment by Provismet** [comment] 2024-01-28 13:56
Tested in a new Modrinth instance with all mods listed.

![image](https://github.com/Provismet/Provi-Origins/assets/17149901/d272c85d-2004-4bbf-a9d2-b9b4ea965bf9)

This bug is unfortunately still not able to be reproduced. The only issue encountered was Apugli crashing my game when hitting a boat.

Do you still experience the bug when my mod is not present?

**Comment by Hal1co** [comment] 2024-01-28 14:00
No, the game works perfectly fine

**Comment by Provismet** [comment] 2024-01-28 14:10
That's very odd, my mod isn't doing anything special so I don't see why it would be tripping up Apoli like this. Or why Apoli would be consistently failing to read its power list.

Can you provide a log of you trying to make a new world? You'll find `latest.log` in the logs folder.  
I will forward this to the Apoli team and see if a solution can be found.

**Comment by Hal1co** [comment] 2024-01-28 14:35
Wait, I created a new world and everything is working o_o
It didn't work earlier when I tried it
The only thing I did was changing my system language to english (so I could send you the screenshot of the mods)
It's very odd indeed o-o
But still thank you so much for helping!

**Comment by Provismet** [comment] 2024-01-28 14:37
That's very odd, I'll pass this along anyway and perhaps there'll be a more permanent fix at some point. Thanks.

**Closed as completed by Provismet** 2024-01-28 14:37 UTC
Labels: bug, duplicate, invalid
