### ISSUE TITLE
Lily of the Void naturalRegeneration gamerule

### ISSUE THREAD

**Issue by MelodyMcKenna** [Provismet/Provi-Origins#3] opened 2023-09-03 18:22 UTC
### Type of Error

Incorrect Behaviour

### Description

The Lily of the Void Origin will naturally regenerate health while at full hunger regardless of the naturalRegeneration gamerule setting.

The naturalRegeneration gamerule applies to the other five Origins in this mod.

### Mod Version

provi-origins-1.4.1

### Minecraft Version

1.19.4

### Mod Loader

Fabric

### Steps to Reproduce

```bash
Minecraft Version 1.20.1 (version 1.19.4 was the only option above)

-Choose Lily of the Void for your Origin
-Use /gamerule naturalRegeneration False
-Player will still regenerate health while at full hunger.
```

### Crash Log

```bash
No crash log
```

**Comment by Provismet** [comment] 2023-09-03 20:49
I can have a fix for this ready for the next release (about a week's time, possibly less).

The issue lies in the `proviorigins:voidlily/fix_regen` power - which was intended to prevent natural regen from being overpowered from the saturation effect.

If your world/server is designed to turn off natural regen entirely, then removing that power would work as a stopgap solution.

For this you can either use the command `/power remove @a proviorigins:voidlily/fix_regen` on a regular interval.  
Or create a datapack with the following file structure to override the existing origin:
```
(root)
-| data
----| proviorigins
-------| origins
-----------| lily_of_the_void.json
```

For the new Lily of the Void json, simply paste in this:
```json
{
	"powers": [
		"proviorigins:voidlily/flower_copy_lily",
		"proviorigins:voidlily/flower_copy_allium",
		"proviorigins:voidlily/flower_copy_azurebluet",
		"proviorigins:voidlily/flower_copy_blueorchid_dandelion",
		"proviorigins:voidlily/flower_copy_cornflower",
		"proviorigins:voidlily/flower_copy_oxeye",
		"proviorigins:voidlily/flower_copy_poppy",
		"proviorigins:voidlily/flower_copy_tulips",
		"proviorigins:voidlily/flower_copy_wither",
		"proviorigins:voidlily/flower_copy_chorus",
		"proviorigins:voidlily/flower_copy_cactus_rose_berry",
		"proviorigins:voidlily/flower_copy_glow",
		"proviorigins:voidlily/flower_copy_wood",
		"proviorigins:voidlily/flower_copy_sugarcane",
		"proviorigins:voidlily/flower_copy_waterbreathing",
		"proviorigins:voidlily/flower_copy__reset_on_death",
		"proviorigins:voidlily/flower_copy__resource",
		"proviorigins:voidlily/flower_copy__manual_reset",
		"proviorigins:voidlily/flower_copy__drain",
		"proviorigins:voidlily/void_growth",
		"proviorigins:voidlily/pollination",
		"proviorigins:voidlily/nether_air",
		"proviorigins:common/no_potions",
		"proviorigins:common/no_splash_potions",
		"proviorigins:common/no_food",
		"proviorigins:common/double_fire_damage",
		"origins:fragile",
		"proviorigins:common/exhaust_more",
		"proviorigins:voidlily/composter_death",
		"proviorigins:voidlily/death_particles",
		"proviorigins:common/ignore_corruption",
		"proviorigins:voidlily/plap_plap_get_bonemealed",
		"extrade:fungifloral"
	],
	"icon": "proviorigins:lily_of_the_void_icon",
	"impact": 3,
	"name": "power.proviorigins.voidlily.name",
	"description": "power.proviorigins.voidlily.description",
	"loading_priority": 1
}
```

**Closed as completed** 2023-09-09 02:10 UTC
Labels: bug
